# Generated by Django 5.2.7 on 2025-11-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
