# Generated by Django 5.2.7 on 2025-11-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_conversation_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
